### ISSUE TITLE
Issue with paginated_orders query causing GroupingError in PostgreSQL

### ISSUE THREAD

**Issue by habibz6deh** [miguelgrinberg/retrofun#4]
I encountered a GroupingError when trying to execute the paginated_orders query in the FastAPI-Alchemical chapter 8 example. Here is the error message:

```bash
sqlalchemy.exc.ProgrammingError: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.GroupingError'>: column "customers_1.id" must appear in the GROUP BY clause or be used in an aggregate function
[SQL: SELECT DISTINCT orders.id, orders.timestamp, orders.customer_id, sum(orders_items.quantity * orders_items.unit_price) AS sum_1, customers_1.id AS id_1, customers_1.name, customers_1.address, customers_1.phone 
FROM orders JOIN customers ON customers.id = orders.customer_id JOIN orders_items ON orders.id = orders_items.order_id JOIN products ON products.id = orders_items.product_id JOIN customers AS customers_1 ON customers_1.id = orders.customer_id GROUP BY orders.id, orders.timestamp, orders.customer_id 
 LIMIT $1::INTEGER OFFSET $2::INTEGER]
[parameters: (10, 0)]
(Background on this error at: https://sqlalche.me/e/20/f405)
```

Environment:
* Python version: 3.12.2
* SQLAlchemy version: 2.0.31
* Database: PostgreSQL
* Driver: asyncpg
* Session Management: [alchemical](https://github.com/miguelgrinberg/alchemical)

**Comment by miguelgrinberg** [comment]
I did not have time to test this, but maybe there is a difference in the version of Postgres that you are using. In the `group_by()` clause, you can try changing `group_by(Order)` to `group_by(Order, Customer)`. Let me know if that helps. In the next couple of days I'll retest this query on the latest Postgres to determine if I need to make an update.

**Comment by habibz6deh** [comment]
I tried adding Customer to the group_by clause alongside Order, but unfortunately, it didn't resolve the issue. I also explored other approaches.

When I pass individual columns to the group_by clause (and the select clause) instead of just the Order model, the query does work. However, we lose the benefit of using the to_dict method because the rows are no longer mapped to our models (instances).

I would like to keep the current structure of the router and the way it executes the query. My main goal is to understand why the current query causes this problem and doesn't execute as expected.

Thank you for your assistance. I appreciate any further insights you might have.

**Comment by miguelgrinberg** [comment]
Okay, yes, I actually reproduced this issue, which happens only with async queries. This is the error that you are getting:

    column "customers_1.id" must appear in the GROUP BY clause or be used in an aggregate function

This is the query that was issued from Python:

```python
       sa.select(Order, total)
            .join(Order.customer)
            .join(Order.order_items)
            .join(OrderItem.product)
            .group_by(Order)
            .distinct()
```

And this is the SQL that SQLAlchemy generated for this query:

```sql
SELECT DISTINCT orders.id, orders.timestamp, orders.customer_id, sum(orders_items.quantity * orders_items.unit_price) AS sum_1, customers_1.id AS id_1, customers_1.name, customers_1.address, customers_1.phone FROM orders
JOIN customers ON customers.id = orders.customer_id
JOIN orders_items ON orders.id = orders_items.order_id
JOIN products ON products.id = orders_items.product_id
JOIN customers AS customers_1 ON customers_1.id = orders.customer_id
GROUP BY orders.id, orders.timestamp, orders.customer_id 
```

Comparing the Python and the SQL you can see that there is an extra `JOIN` clause in the SQL that is not in the Python query, the last one:

```sql
JOIN customers AS customers_1 ON customers_1.id = orders.customer_id
```

The error occurs because the query does not indicate how the data coming from this join should be grouped, and obviously this happens because the join is being added by SQLAlchemy.

Why is this join added? This happens because the `Order` model has a `customer` relationship that is configured to be retrieved with a join:

```python
class Order(Model):
    # ...
    customer: so.Mapped['Customer'] = so.relationship(
        lazy='joined', innerjoin=True, back_populates='orders')
```

In standard SQLAlchemy joins like this one are loaded lazily, but when using asyncio lazy joins cannot be used (as covered in the book), so I changed some of the joins to `joined` (SQLAlchemy adds a join to all queries to retrieve this data), and others to `selectin` (SQlAlchemy retrieves this data with a `SELECT IN` query).

The problem is that for queries that use grouping, having a join that is automatically added can interfere with the group clause. One possible solution is to switch this join to use `selectin`:

```python
       sa.select(Order, total)
            .options(so.selectinload(Order.customer))
            .join(Order.customer)
            .join(Order.order_items)
            .join(OrderItem.product)
            .group_by(Order)
            .distinct()
```

Or it can also be made permanent by changing the relationship:

```python
class Order(Model):
    # ...
    customer: so.Mapped['Customer'] = so.relationship(
        lazy='selectin', innerjoin=True, back_populates='orders')
```

The issue here, in my opinion, is that SQLAlchemy should realize that we have issued a join to customers, so it does not need to add yet another one, but it does not appear that it can detect this and for that reason we need to change the loading method to `selectin`.

**Comment by miguelgrinberg** [comment]
There is a second problem that I also missed, that exists in both the sync and async versions of this query. The problem occurs when clicking on the Customer column to sort by customer name, which triggers the following error:

```
for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 2: ...id, orders.timestamp, orders.customer_id ORDER BY customers....
                                                             ^
```

Here Postgres is saying that any columns that are used in the `ORDER BY` part should be in the `SELECT` part as well. The solution to this is to add the customer to the select and group_by clauses:

```python
        sa.select(Order, total, Customer)
            .options(so.selectinload(Order.customer))
            .join(Order.customer)
            .join(Order.order_items)
            .join(OrderItem.product)
            .group_by(Order, Customer)
            .distinct()
```

**Comment by habibz6deh** [comment]
I really appreciate your prompt response and support.
